-- Kemne Jabo — Supabase schema (PRD §8.4, §9, §10)
-- Run this once in the Supabase SQL editor, then run supabase/seed.sql (generated by `node tools/export-sql.mjs`).
-- The browser only ever calls the functions at the bottom, with the public anon key.
-- Tables are not writable directly: row-level security blocks it, and the functions do the checks.

create table if not exists stops (
  id text primary key, name_bn text not null, name_en text not null,
  aliases text[] not null default '{}', lat double precision not null, lng double precision not null
);
create table if not exists routes (
  id text primary key, name_bn text not null, name_en text not null, company text default '',
  service_type text not null check (service_type in ('bus', 'minibus')), hours text,
  frequency_min int, frequency_max int, verified boolean not null default false, last_checked date
);
create table if not exists route_stops (
  route_id text references routes(id) on delete cascade, stop_id text references stops(id),
  sequence int not null, primary key (route_id, sequence)
);
create index if not exists route_stops_stop on route_stops (stop_id);
create table if not exists area_hints (
  id text primary key, area_name text not null, hint_text_bn text, hint_text_en text, nearest_stop_id text references stops(id)
);
create table if not exists settings (key text primary key, value jsonb not null);

-- Rider data. device_hash is a salted SHA-256 of a random id kept on the phone; it exists only to limit spam.
create table if not exists bus_seen (
  id bigint generated always as identity primary key,
  route_id text not null references routes(id), stop_id text not null references stops(id),
  created_at timestamptz not null default now(), device_hash text not null
);
create index if not exists bus_seen_recent on bus_seen (route_id, created_at desc);
create index if not exists bus_seen_device on bus_seen (device_hash, created_at desc);

create table if not exists bus_seen_wrong (
  id bigint generated always as identity primary key,
  route_id text not null, stop_id text not null, created_at timestamptz not null default now(), device_hash text not null
);

create table if not exists fare_reports (
  id bigint generated always as identity primary key,
  route_id text not null references routes(id), from_stop text not null, to_stop text not null,
  amount int not null check (amount between 1 and 999),
  created_at timestamptz not null default now(), device_hash text not null
);
create index if not exists fare_trip on fare_reports (route_id, from_stop, to_stop);

create table if not exists route_flags (
  id bigint generated always as identity primary key,
  route_id text, kind text not null, note text, extra jsonb, created_at timestamptz not null default now(), device_hash text not null
);

-- ───────────── row-level security ─────────────
alter table stops enable row level security;       create policy "read stops" on stops for select using (true);
alter table routes enable row level security;      create policy "read routes" on routes for select using (true);
alter table route_stops enable row level security; create policy "read route_stops" on route_stops for select using (true);
alter table area_hints enable row level security;  create policy "read area_hints" on area_hints for select using (true);
alter table settings enable row level security;    create policy "read settings" on settings for select using (true);
-- Rider tables: RLS on, no policies → nobody can read or write them directly. Only the functions below can.
alter table bus_seen enable row level security;
alter table bus_seen_wrong enable row level security;
alter table fare_reports enable row level security;
alter table route_flags enable row level security;

-- ───────────── functions the site calls ─────────────

-- Bus seen: validates, rate-limits (10 min per bus+stop, 20/day per device), stores bus + stop + time only.
create or replace function report_seen(p_route text, p_stop text, p_device text) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  if length(p_device) < 16 then return jsonb_build_object('ok', false, 'reason', 'invalid'); end if;
  if not exists (select 1 from route_stops where route_id = p_route and stop_id = p_stop) then
    return jsonb_build_object('ok', false, 'reason', 'invalid');   -- the bus must actually serve that stop
  end if;
  if exists (select 1 from bus_seen where device_hash = p_device and route_id = p_route and stop_id = p_stop
             and created_at > now() - interval '10 minutes') then
    return jsonb_build_object('ok', false, 'reason', 'rate');
  end if;
  if (select count(*) from bus_seen where device_hash = p_device and created_at > now() - interval '1 day') >= 20 then
    return jsonb_build_object('ok', false, 'reason', 'day');
  end if;
  insert into bus_seen (route_id, stop_id, device_hash) values (p_route, p_stop, p_device);
  return jsonb_build_object('ok', true);
end $$;

-- Reports still inside the visible window, grouped per bus + stop, with how many different devices reported.
-- A group is hidden when at least as many devices called it wrong as confirmed it.
create or replace function seen_recent(p_routes text[], p_ttl_min int default 30)
returns table (route_id text, stop_id text, last_at timestamptz, riders bigint)
language sql security definer stable set search_path = public as $$
  select s.route_id, s.stop_id, max(s.created_at) as last_at, count(distinct s.device_hash) as riders
  from bus_seen s
  where s.route_id = any(p_routes) and s.created_at > now() - make_interval(mins => least(greatest(p_ttl_min, 1), 120))
  group by s.route_id, s.stop_id
  having count(distinct s.device_hash) > (
    select count(distinct w.device_hash) from bus_seen_wrong w
    where w.route_id = s.route_id and w.stop_id = s.stop_id and w.created_at > now() - interval '2 hours')
$$;

create or replace function report_seen_wrong(p_route text, p_stop text, p_device text) returns void
language sql security definer set search_path = public as $$
  insert into bus_seen_wrong (route_id, stop_id, device_hash)
  select p_route, p_stop, p_device where length(p_device) >= 16
    and not exists (select 1 from bus_seen_wrong where device_hash = p_device and route_id = p_route and stop_id = p_stop
                    and created_at > now() - interval '30 minutes');
$$;

-- Fare feedback: 10 per device per day; amounts far from the official fare are dropped when the middle range is computed (client side).
create or replace function report_fare(p_route text, p_from text, p_to text, p_amount int, p_device text) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  if length(p_device) < 16 or p_amount < 1 or p_amount > 999
     or not exists (select 1 from route_stops where route_id = p_route and stop_id = p_from)
     or not exists (select 1 from route_stops where route_id = p_route and stop_id = p_to) then
    return jsonb_build_object('ok', false, 'reason', 'invalid');
  end if;
  if (select count(*) from fare_reports where device_hash = p_device and created_at > now() - interval '1 day') >= 10 then
    return jsonb_build_object('ok', false, 'reason', 'day');
  end if;
  insert into fare_reports (route_id, from_stop, to_stop, amount, device_hash) values (p_route, p_from, p_to, p_amount, p_device);
  return jsonb_build_object('ok', true);
end $$;

-- Amounts only (no devices, no times) for one trip, newest 500 in the last 60 days.
create or replace function fare_amounts(p_route text, p_from text, p_to text) returns int[]
language sql security definer stable set search_path = public as $$
  select coalesce(array_agg(amount), '{}') from (
    select amount from fare_reports
    where route_id = p_route and from_stop = p_from and to_stop = p_to and created_at > now() - interval '60 days'
    order by created_at desc limit 500) t
$$;

-- Wrong-info reports, "was this route correct?" answers and missing-trip requests.
create or replace function report_flag(p_route text, p_kind text, p_note text, p_extra jsonb, p_device text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if length(p_device) < 16 or p_kind !~ '^[a-z_]{2,30}$' then return; end if;
  if (select count(*) from route_flags where device_hash = p_device and created_at > now() - interval '1 day') >= 30 then return; end if;
  insert into route_flags (route_id, kind, note, extra, device_hash) values (p_route, p_kind, left(coalesce(p_note, ''), 300), p_extra, p_device);
end $$;

revoke all on function report_seen, seen_recent, report_seen_wrong, report_fare, fare_amounts, report_flag from public;
grant execute on function report_seen, seen_recent, report_seen_wrong, report_fare, fare_amounts, report_flag to anon, authenticated;

-- ───────────── housekeeping ─────────────
-- Bus-seen rows are useless after the visible window; deleting them keeps the free tier small.
-- Enable pg_cron in Supabase (Database → Extensions), then:
--   select cron.schedule('kj-expire-seen', '*/15 * * * *', $$ delete from bus_seen where created_at < now() - interval '3 hours';
--                                                             delete from bus_seen_wrong where created_at < now() - interval '3 hours'; $$);
-- Back up the route tables regularly (Table editor → Export as CSV, or `pg_dump`) — free projects can be paused.
