// Generates supabase/seed.sql from data/*.json so the database knows which bus serves which stop.
//   node tools/export-sql.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const load = (n) => JSON.parse(fs.readFileSync(path.join(root, "data", n), "utf8"));
const stops = load("stops.json"), routes = load("routes.json"), areas = load("areas.json"), settings = load("settings.json");

const q = (v) => (v == null || v === "" ? "null" : "'" + String(v).replace(/'/g, "''") + "'");
const arr = (a) => "array[" + a.map(q).join(", ") + "]::text[]";
const out = ["-- generated by tools/export-sql.mjs — do not edit by hand", "begin;", "-- safe to re-run: upserts stops/routes/settings, rewrites route_stops and area_hints, never touches rider data",
  "delete from route_stops;", "delete from area_hints;"];

for (const s of stops) out.push(`insert into stops values (${q(s.id)}, ${q(s.name_bn)}, ${q(s.name_en)}, ${arr(s.aliases)}, ${s.lat}, ${s.lng}) on conflict (id) do update set name_bn = excluded.name_bn, name_en = excluded.name_en, aliases = excluded.aliases, lat = excluded.lat, lng = excluded.lng;`);
for (const r of routes) out.push(`insert into routes values (${q(r.id)}, ${q(r.name_bn)}, ${q(r.name_en)}, ${q(r.company)}, ${q(r.service_type)}, ${q(r.hours)}, ${r.frequency_min}, ${r.frequency_max}, ${r.verified}, ${q(r.last_checked)}) on conflict (id) do update set name_bn = excluded.name_bn, name_en = excluded.name_en, company = excluded.company, service_type = excluded.service_type, hours = excluded.hours, frequency_min = excluded.frequency_min, frequency_max = excluded.frequency_max, verified = excluded.verified, last_checked = excluded.last_checked;`);
for (const r of routes) r.stops.forEach((sid, i) => out.push(`insert into route_stops values (${q(r.id)}, ${q(sid)}, ${i + 1});`));
for (const a of areas) out.push(`insert into area_hints values (${q(a.id)}, ${q(a.name_en)}, ${q(a.hint_text_bn)}, ${q(a.hint_text_en)}, ${q(a.nearest_stop_id)});`);
for (const [k, v] of Object.entries(settings)) if (!k.startsWith("_")) out.push(`insert into settings values (${q(k)}, '${JSON.stringify(v).replace(/'/g, "''")}'::jsonb) on conflict (key) do update set value = excluded.value;`);
out.push("commit;");

fs.writeFileSync(path.join(root, "supabase", "seed.sql"), out.join("\n") + "\n");
console.log(`seed.sql: ${stops.length} stops, ${routes.length} routes, ${areas.length} area hints`);
