// Seed data for Kemne Jabo. Hand-compiled starter set — every route here is
// "not yet verified" until someone rides it. Coordinates are first guesses;
// tools/build-data.mjs cross-checks them against OpenStreetMap (Nominatim).
//
// stop: [id, name_en, name_bn, lat, lng, osm_query, aliases[]]

export const STOPS = [
  ["gazipur-chourasta", "Gazipur Chourasta", "গাজীপুর চৌরাস্তা", 23.9996, 90.4203, "Gazipur Chourasta", ["gazipur", "gazipur chowrasta", "গাজীপুর", "joydebpur", "জয়দেবপুর"]],
  ["tongi", "Tongi", "টঙ্গী", 23.8920, 90.4040, "Tongi Station Road", ["tongi bazar", "টঙ্গী বাজার", "tongi station"]],
  ["abdullahpur", "Abdullahpur", "আব্দুল্লাহপুর", 23.8797, 90.4006, "Abdullahpur Uttara", ["abdullapur", "abdullahpur uttara", "আবদুল্লাহপুর", "আব্দুল্লাপুর"]],
  ["uttara-hb", "Uttara House Building", "উত্তরা হাউজ বিল্ডিং", 23.8738, 90.3994, "House Building Uttara", ["house building", "uttara hb", "hb uttara", "uttara", "উত্তরা", "হাউস বিল্ডিং", "হাউজবিল্ডিং", "উত্তরা হাউসবিল্ডিং"]],
  ["azampur", "Azampur", "আজমপুর", 23.8672, 90.4003, "Azampur Uttara", ["ajampur", "আজমপুর"]],
  ["rajlokkhi", "Rajlokkhi", "রাজলক্ষ্মী", 23.8641, 90.4003, "Rajlokkhi Uttara", ["rajlakshmi", "razlokkhi", "rajlaxmi", "রাজলক্ষী"]],
  ["jashimuddin", "Jashimuddin", "জসীমউদ্দীন", 23.8607, 90.3997, "Jasimuddin Uttara", ["jasimuddin", "jasim uddin", "jashim uddin", "জসিমউদ্দিন", "জসীম উদ্দীন"]],
  ["airport", "Airport", "এয়ারপোর্ট", 23.8517, 90.4040, "Hazrat Shahjalal International Airport", ["biman bandar", "বিমানবন্দর", "shahjalal airport", "hazrat shahjalal", "airport road"]],
  ["khilkhet", "Khilkhet", "খিলক্ষেত", 23.8290, 90.4210, "Khilkhet Dhaka", ["khilkhet", "খিলখেত"]],
  ["kuril", "Kuril Bishwa Road", "কুড়িল বিশ্বরোড", 23.8210, 90.4215, "Kuril Flyover Dhaka", ["kuril", "kuril", "কুড়িল", "কুরিল", "bishwa road", "বিশ্বরোড", "kuril flyover"]],
  ["jamuna-future-park", "Jamuna Future Park", "যমুনা ফিউচার পার্ক", 23.8137, 90.4247, "Jamuna Future Park", ["jfp", "jamuna", "future park", "যমুনা", "জেএফপি"]],
  ["bashundhara", "Bashundhara R/A", "বসুন্ধরা", 23.8190, 90.4310, "Bashundhara Residential Area Dhaka", ["bashundhara", "bashundhara ra", "bosundhara", "basundhara", "বসুন্ধরা আবাসিক", "বসুন্ধরা গেট"]],
  ["notun-bazar", "Notun Bazar", "নতুন বাজার", 23.7983, 90.4222, "Natun Bazar Dhaka", ["natun bazar", "nutun bazar", "nadda", "নদ্দা", "নতুনবাজার", "uttar badda", "উত্তর বাড্ডা"]],
  ["badda", "Badda", "বাড্ডা", 23.7800, 90.4255, "Madhya Badda Dhaka", ["madhya badda", "merul badda", "মধ্য বাড্ডা", "মেরুল বাড্ডা", "বাড্ডা"]],
  ["gulshan-2", "Gulshan 2", "গুলশান ২", 23.7948, 90.4144, "Gulshan 2 Circle Dhaka", ["gulshan two", "gulshan circle 2", "গুলশান দুই", "গুলশান-২", "গুলশান ২ নম্বর"]],
  ["gulshan-1", "Gulshan 1", "গুলশান ১", 23.7806, 90.4167, "Gulshan 1 Circle Dhaka", ["gulshan one", "gulshan circle 1", "গুলশান এক", "গুলশান-১", "গুলশান ১ নম্বর"]],
  ["banani", "Banani", "বনানী", 23.7937, 90.4066, "Banani Dhaka", ["bonani", "বনানি"]],
  ["kakoli", "Kakoli", "কাকলী", 23.7972, 90.4009, "Kakoli Dhaka", ["kakoli bus stand", "কাকলি"]],
  ["mohakhali", "Mohakhali", "মহাখালী", 23.7782, 90.4007, "Mohakhali Dhaka", ["mohakhali bus terminal", "mohakhali flyover", "মহাখালি", "মহাখালী বাস টার্মিনাল", "jahangir gate", "জাহাঙ্গীর গেট"]],
  ["farmgate", "Farmgate", "ফার্মগেট", 23.7590, 90.3871, "Farmgate Dhaka", ["farm gate", "farmget", "ফার্ম গেট", "ফার্মগেট"]],
  ["karwan-bazar", "Karwan Bazar", "কারওয়ান বাজার", 23.7510, 90.3930, "Kawran Bazar Dhaka", ["kawran bazar", "karwan bazaar", "kawranbazar", "কাওরান বাজার", "কারওয়ানবাজার"]],
  ["bangla-motor", "Bangla Motor", "বাংলামোটর", 23.7468, 90.3916, "Bangla Motor Dhaka", ["banglamotor", "bangla mor", "বাংলা মোটর"]],
  ["panthapath", "Panthapath", "পান্থপথ", 23.7527, 90.3860, "Panthapath Dhaka", ["panthopath", "পান্থপথ"]],
  ["kalabagan", "Kalabagan", "কলাবাগান", 23.7480, 90.3830, "Kalabagan Dhaka", ["kolabagan", "কলাবাগান"]],
  ["science-lab", "Science Lab", "সায়েন্স ল্যাব", 23.7388, 90.3836, "Science Laboratory Dhaka", ["science laboratory", "sciencelab", "science lab crossing", "সায়েন্সল্যাব", "সাইন্স ল্যাব"]],
  ["dhanmondi-27", "Dhanmondi 27", "ধানমন্ডি ২৭", 23.7545, 90.3735, "Dhanmondi 27 Dhaka", ["dhanmondi 27 number", "dhanmondi twenty seven", "ধানমন্ডি সাতাশ", "ধানমণ্ডি ২৭"]],
  ["jigatola", "Jigatola (Dhanmondi 15)", "জিগাতলা", 23.7395, 90.3730, "Jigatola Dhaka", ["dhanmondi 15", "zigatola", "jigatola bus stand", "ধানমন্ডি ১৫", "ধানমন্ডি পনেরো", "যিগাতলা"]],
  ["new-market", "New Market", "নিউ মার্কেট", 23.7340, 90.3855, "New Market Dhaka", ["newmarket", "new market dhaka", "নিউমার্কেট"]],
  ["nilkhet", "Nilkhet", "নীলক্ষেত", 23.7330, 90.3880, "Nilkhet Dhaka", ["neelkhet", "nilkhet babupura", "নীলখেত", "নিলক্ষেত"]],
  ["azimpur", "Azimpur", "আজিমপুর", 23.7287, 90.3865, "Azimpur Dhaka", ["azimpur", "azimpur bus stand", "আজিমপুর"]],
  ["tsc", "TSC (Dhaka University)", "টিএসসি (ঢাকা বিশ্ববিদ্যালয়)", 23.7337, 90.3955, "Teacher Student Centre Dhaka University", ["tsc", "dhaka university", "du", "doel chattar", "ঢাকা বিশ্ববিদ্যালয়", "ঢাবি", "টিএসসি", "দোয়েল চত্বর", "ঢাকা ভার্সিটি", "dhaka varsity"]],
  ["shahbag", "Shahbag", "শাহবাগ", 23.7391, 90.3950, "Shahbag Dhaka", ["shahbagh", "shahbug", "শাহবাগ", "শাহবাগ মোড়", "বারডেম", "pg hospital", "পিজি হাসপাতাল", "bsmmu"]],
  ["hatirpool", "Hatirpool", "হাতিরপুল", 23.7405, 90.3865, "Hatirpool Dhaka", ["hatir pool", "hatirpul", "হাতিরপুল"]],
  ["moghbazar", "Moghbazar", "মগবাজার", 23.7512, 90.4040, "Moghbazar Dhaka", ["mogbazar", "mogh bazar", "mogbazaar", "মগবাজার", "মগ বাজার"]],
  ["mouchak", "Mouchak", "মৌচাক", 23.7455, 90.4108, "Mouchak Dhaka", ["mauchak", "moucahk", "mowchak", "মৌচাক"]],
  ["malibagh", "Malibagh", "মালিবাগ", 23.7480, 90.4170, "Malibagh Dhaka", ["malibag", "malibagh rail gate", "মালিবাগ"]],
  ["shantinagar", "Shantinagar", "শান্তিনগর", 23.7378, 90.4130, "Shantinagar Dhaka", ["shanti nagar", "santinagar", "শান্তিনগর", "শান্তি নগর"]],
  ["rampura", "Rampura", "রামপুরা", 23.7615, 90.4250, "Rampura Bridge Dhaka", ["rampura bridge", "rampura tv", "রামপুরা ব্রিজ", "রামপুরা টিভি সেন্টার", "ramprua"]],
  ["banasree", "Banasree", "বনশ্রী", 23.7600, 90.4330, "Banasree Dhaka", ["bonosree", "banashree", "banasri", "বনশ্রী"]],
  ["khilgaon", "Khilgaon", "খিলগাঁও", 23.7480, 90.4290, "Khilgaon Dhaka", ["khilgaon railgate", "khilgaon rail gate", "খিলগাঁও", "খিলগাও"]],
  ["press-club", "Press Club", "প্রেস ক্লাব", 23.7312, 90.4090, "Jatiya Press Club Dhaka", ["pressclub", "jatiya press club", "জাতীয় প্রেসক্লাব", "প্রেসক্লাব", "segunbagicha", "সেগুনবাগিচা"]],
  ["paltan", "Paltan", "পল্টন", 23.7345, 90.4120, "Paltan Dhaka", ["poltan", "paltan more", "পল্টন", "পল্টন মোড়", "bijoynagar", "বিজয়নগর"]],
  ["gulistan", "Gulistan", "গুলিস্তান", 23.7260, 90.4115, "Gulistan Dhaka", ["golistan", "gulistan stand", "গুলিস্থান", "গুলিস্তান", "গোলিস্তান"]],
  ["motijheel", "Motijheel", "মতিঝিল", 23.7330, 90.4195, "Motijheel Shapla Chattar Dhaka", ["motijil", "moti jheel", "motijhil", "motijheel shapla chattar", "shapla chattar", "মতিঝিল", "মতিঝিল শাপলা চত্বর", "মতিজিল", "মতিঝিল", "dilkusha", "দিলকুশা"]],
  ["arambagh", "Arambagh", "আরামবাগ", 23.7365, 90.4200, "Arambagh Dhaka", ["arambag", "আরামবাগ"]],
  ["kamalapur", "Kamalapur", "কমলাপুর", 23.7310, 90.4260, "Kamalapur Railway Station Dhaka", ["komlapur", "kamlapur", "kamalapur station", "কমলাপুর রেলস্টেশন", "কমলাপুর"]],
  ["sayedabad", "Sayedabad", "সায়েদাবাদ", 23.7110, 90.4290, "Sayedabad Bus Terminal Dhaka", ["saidabad", "sayedabad bus terminal", "shaydabad", "সায়েদাবাদ বাস টার্মিনাল", "সায়দাবাদ", "সায়েদাবাদ"]],
  ["jatrabari", "Jatrabari", "যাত্রাবাড়ী", 23.7101, 90.4337, "Jatrabari Dhaka", ["jatrabari", "jatrabari crossing", "zatrabari", "যাত্রাবাড়ি", "যাত্রাবাড়ী মোড়"]],
  ["sign-board", "Sign Board", "সাইন বোর্ড", 23.6935, 90.4800, "", ["signboard", "সাইনবোর্ড"]],
  ["matuail", "Matuail", "মাতুয়াইল", 23.7050, 90.4640, "", ["matuyail"]],
  ["rayerbag", "Rayerbag", "রায়েরবাগ", 23.7055, 90.4550, "", ["rayer bag"]],
  ["shonir-akhra", "Shonir Akhra", "শনির আখড়া", 23.7040, 90.4470, "", ["shanir akhra", "শনির আখরা"]],
  ["nawabpur", "Nawabpur", "নবাবপুর", 23.7160, 90.4125, "Nawabpur Road Dhaka", ["nowabpur", "নবাবপুর রোড", "নবাবপুর"]],
  ["sadarghat", "Sadarghat", "সদরঘাট", 23.7060, 90.4065, "Sadarghat Launch Terminal Dhaka", ["sodorghat", "sadar ghat", "sadarghat launch terminal", "সদর ঘাট", "সদরঘাট লঞ্চ টার্মিনাল", "launch ghat", "লঞ্চঘাট"]],
  ["savar", "Savar", "সাভার", 23.8466, 90.2575, "Savar Bus Stand", ["savar bus stand", "shavar", "সাভার বাস স্ট্যান্ড", "সাভার"]],
  ["aminbazar", "Aminbazar", "আমিনবাজার", 23.7880, 90.3200, "Aminbazar Dhaka", ["amin bazar", "aminbazar bridge", "আমিন বাজার"]],
  ["gabtoli", "Gabtoli", "গাবতলী", 23.7783, 90.3450, "Gabtoli Bus Terminal Dhaka", ["gabtali", "gabtoli bus terminal", "gabtoli bridge", "গাবতলি", "গাবতলী বাস টার্মিনাল"]],
  ["technical", "Technical", "টেকনিক্যাল", 23.7838, 90.3541, "Technical More Dhaka", ["technical more", "technical mor", "টেকনিক্যাল মোড়", "টেকনিকাল"]],
  ["kallyanpur", "Kallyanpur", "কল্যাণপুর", 23.7795, 90.3607, "Kallyanpur Dhaka", ["kalyanpur", "kollanpur", "kallyanpur bus stand", "কল্যাণপুর"]],
  ["shyamoli", "Shyamoli", "শ্যামলী", 23.7742, 90.3650, "Shyamoli Square Dhaka", ["shamoli", "shyamoli square", "syamoli", "shamoly", "শ্যামলি", "শ্যামলী স্কয়ার"]],
  ["asad-gate", "Asad Gate", "আসাদ গেট", 23.7625, 90.3745, "Asad Gate Dhaka", ["asadgate", "asad get", "আসাদগেট", "আসাদ গেইট"]],
  ["mohammadpur", "Mohammadpur", "মোহাম্মদপুর", 23.7590, 90.3620, "Mohammadpur Town Hall Dhaka", ["mohammadpur town hall", "town hall", "muhammadpur", "mohammedpur", "মুহাম্মদপুর", "মোহাম্মদপুর টাউন হল", "টাউন হল", "mohammadpur bus stand"]],
  ["mirpur-1", "Mirpur 1", "মিরপুর ১", 23.7957, 90.3535, "Mirpur 1 Dhaka", ["mirpur one", "mirpur 1 number", "mirpur-1", "মিরপুর এক", "মিরপুর-১", "মিরপুর ১ নম্বর", "mirpur 1 bus stand"]],
  ["mirpur-2", "Mirpur 2", "মিরপুর ২", 23.8062, 90.3550, "Mirpur 2 Dhaka", ["mirpur two", "mirpur-2", "মিরপুর দুই", "মিরপুর-২", "মিরপুর ২ নম্বর", "mirpur stadium"]],
  ["mirpur-10", "Mirpur 10", "মিরপুর ১০", 23.8069, 90.3685, "Mirpur 10 Golchattar Dhaka", ["mirpur ten", "mirpur-10", "mirpur 10 golchattar", "mirpur 10 gol chattar", "mirpur dosh", "মিরপুর দশ", "মিরপুর-১০", "মিরপুর ১০ গোলচত্বর", "মিরপুর ১০ নম্বর", "মিরপুর টেন"]],
  ["mirpur-11", "Mirpur 11", "মিরপুর ১১", 23.8180, 90.3650, "Mirpur 11 Dhaka", ["mirpur eleven", "mirpur-11", "মিরপুর এগারো", "মিরপুর-১১", "মিরপুর ১১ নম্বর", "mirpur egaro"]],
  ["mirpur-12", "Mirpur 12", "মিরপুর ১২", 23.8275, 90.3640, "Mirpur 12 Dhaka", ["mirpur twelve", "mirpur-12", "mirpur baro", "মিরপুর বারো", "মিরপুর-১২", "মিরপুর ১২ নম্বর", "মিরপুর বার"]],
  ["mirpur-14", "Mirpur 14", "মিরপুর ১৪", 23.7990, 90.3860, "Mirpur 14 Dhaka", ["mirpur fourteen", "mirpur-14", "mirpur choddo", "মিরপুর চৌদ্দ", "মিরপুর-১৪", "মিরপুর ১৪ নম্বর"]],
  ["pallabi", "Pallabi", "পল্লবী", 23.8250, 90.3680, "Pallabi Dhaka", ["polli", "pollobi", "পল্লবি", "পল্লবী"]],
  ["kalshi", "Kalshi", "কালশী", 23.8340, 90.3790, "Kalshi Mirpur Dhaka", ["kalsi", "kalshi road", "কালসী", "কালশী রোড"]],
  ["kazipara", "Kazipara", "কাজীপাড়া", 23.7990, 90.3727, "Kazipara Mirpur Dhaka", ["kazi para", "kajipara", "কাজিপাড়া", "কাজী পাড়া"]],
  ["shewrapara", "Shewrapara", "শেওড়াপাড়া", 23.7905, 90.3755, "Shewrapara Dhaka", ["sheorapara", "sewrapara", "shewra para", "শেওড়া পাড়া", "শেওরাপাড়া"]],
  ["agargaon", "Agargaon", "আগারগাঁও", 23.7780, 90.3800, "Agargaon Dhaka", ["agargoan", "agargaon taltola", "taltola", "তালতলা", "আগারগাও", "আগারগাঁও তালতলা"]],
];

// area: [id, name_en, name_bn, lat, lng, osm_query, aliases[], hint_en, hint_bn]
// hint may be "" — the app then falls back to "nearest stop" guidance.
export const AREAS = [
  ["bashundhara-road-36", "Bashundhara Road 36", "বসুন্ধরা রোড ৩৬", 23.8195, 90.4375, "Bashundhara Dhaka", ["road 36 bashundhara", "bashundhara 36", "বসুন্ধরা ৩৬ নম্বর রোড"],
    "No bus runs inside the block. Take a rickshaw to the main road, then ride to Jamuna Future Park or Kuril.",
    "ব্লকের ভেতরে বাস চলে না। রিকশায় মেইন রোডে এসে যমুনা ফিউচার পার্ক বা কুড়িলের বাস ধরুন।"],
  ["bashundhara-block-d", "Bashundhara Block D", "বসুন্ধরা ডি ব্লক", 23.8175, 90.4335, "Bashundhara Dhaka", ["block d bashundhara", "বসুন্ধরা ব্লক ডি"], "", ""],
  ["mirpur-dohs", "Mirpur DOHS", "মিরপুর ডিওএইচএস", 23.8300, 90.3830, "Mirpur DOHS Dhaka", ["dohs mirpur", "মিরপুর ডিওএইচএস", "ডিওএইচএস মিরপুর"],
    "Walk or take a rickshaw out to the main road, then catch a bus at Mirpur 12 or Kalshi.",
    "মেইন রোডে বেরিয়ে মিরপুর ১২ বা কালশী থেকে বাস ধরুন।"],
  ["senpara-parbata", "Senpara Parbata", "সেনপাড়া পর্বতা", 23.8100, 90.3730, "Senpara Parbata Dhaka", ["senpara", "সেনপাড়া"], "", ""],
  ["monipur", "Monipur", "মনিপুর", 23.8040, 90.3580, "Monipur Mirpur Dhaka", ["মনিপুর"], "", ""],
  ["shah-ali-bagh", "Shah Ali Bagh", "শাহ আলী বাগ", 23.8130, 90.3590, "Shah Ali Mazar Mirpur Dhaka", ["shah ali", "mazar road mirpur", "শাহ আলী"], "", ""],
  ["rupnagar", "Rupnagar", "রূপনগর", 23.8030, 90.3480, "Rupnagar Mirpur Dhaka", ["rupnagar abasik", "রূপনগর আবাসিক"], "", ""],
  ["mirpur-6", "Mirpur Section 6", "মিরপুর ৬ নম্বর সেকশন", 23.8160, 90.3600, "Mirpur 6 Dhaka", ["mirpur 6", "section 6 mirpur", "মিরপুর ৬", "মিরপুর সেকশন ৬"], "", ""],
  ["ahmednagar", "Ahmednagar", "আহমেদনগর", 23.8190, 90.3720, "Ahmednagar Paikpara Dhaka", ["paikpara", "পাইকপাড়া", "আহমদনগর"], "", ""],
  ["uttara-sector-3", "Uttara Sector 3", "উত্তরা সেক্টর ৩", 23.8590, 90.3940, "Uttara Sector 3 Dhaka", ["sector 3 uttara", "উত্তরা ৩ নম্বর সেক্টর", "উত্তরা সেক্টর তিন"],
    "Come out to Airport Road (Jashimuddin / Rajlokkhi side) to board.",
    "এয়ারপোর্ট রোডে (জসীমউদ্দীন বা রাজলক্ষ্মীর দিকে) এসে বাসে উঠুন।"],
  ["uttara-sector-4", "Uttara Sector 4", "উত্তরা সেক্টর ৪", 23.8630, 90.3950, "Uttara Sector 4 Dhaka", ["sector 4 uttara", "উত্তরা ৪ নম্বর সেক্টর"], "", ""],
  ["uttara-sector-7", "Uttara Sector 7", "উত্তরা সেক্টর ৭", 23.8720, 90.3930, "Uttara Sector 7 Dhaka", ["sector 7 uttara", "উত্তরা ৭ নম্বর সেক্টর"], "", ""],
  ["uttara-sector-10", "Uttara Sector 10", "উত্তরা সেক্টর ১০", 23.8760, 90.3860, "Uttara Sector 10 Dhaka", ["sector 10 uttara", "উত্তরা ১০ নম্বর সেক্টর"], "", ""],
  ["uttara-sector-11", "Uttara Sector 11", "উত্তরা সেক্টর ১১", 23.8810, 90.3900, "Uttara Sector 11 Dhaka", ["sector 11 uttara", "উত্তরা ১১ নম্বর সেক্টর"], "", ""],
  ["uttara-sector-14", "Uttara Sector 14", "উত্তরা সেক্টর ১৪", 23.8890, 90.3960, "Uttara Sector 14 Dhaka", ["sector 14 uttara"], "", ""],
  ["banani-dohs", "Banani DOHS", "বনানী ডিওএইচএস", 23.7960, 90.3960, "Banani DOHS Dhaka", ["dohs banani", "বনানী ডিওএইচএস"], "", ""],
  ["baridhara", "Baridhara", "বারিধারা", 23.8010, 90.4200, "Baridhara Dhaka", ["baridhara diplomatic zone", "bari dhara", "বারিধারা ডিপ্লোমেটিক জোন"],
    "Walk or take a rickshaw to Gulshan 2 circle, then catch a bus.",
    "হেঁটে বা রিকশায় গুলশান ২ নম্বর গোলচত্বরে এসে বাস ধরুন।"],
  ["niketon", "Niketon", "নিকেতন", 23.7770, 90.4170, "Niketon Gulshan Dhaka", ["niketan", "নিকেতন"], "", ""],
  ["mohakhali-dohs", "Mohakhali DOHS", "মহাখালী ডিওএইচএস", 23.7830, 90.3960, "Mohakhali DOHS Dhaka", ["dohs mohakhali"], "", ""],
  ["lalmatia", "Lalmatia", "লালমাটিয়া", 23.7575, 90.3700, "Lalmatia Dhaka", ["lalmatiya", "লালমাটিয়া"],
    "Take a rickshaw to Asad Gate or Dhanmondi 27 main road, then board.",
    "রিকশায় আসাদ গেট বা ধানমন্ডি ২৭-এর মেইন রোডে এসে বাস ধরুন।"],
  ["dhanmondi-road-8", "Dhanmondi Road 8A", "ধানমন্ডি ৮/এ", 23.7500, 90.3720, "Dhanmondi 8A Dhaka", ["dhanmondi 8a", "dhanmondi road 8"], "", ""],
  ["shankar", "Shankar", "শঙ্কর", 23.7440, 90.3690, "Shankar Dhanmondi Dhaka", ["shonkor", "শংকর"], "", ""],
  ["adabor", "Adabor", "আদাবর", 23.7700, 90.3580, "Adabor Dhaka", ["adabar", "আদাবর"], "", ""],
  ["tajmahal-road", "Taj Mahal Road", "তাজমহল রোড", 23.7640, 90.3620, "Taj Mahal Road Mohammadpur Dhaka", ["tajmahal road mohammadpur", "তাজমহল রোড মোহাম্মদপুর"], "", ""],
  ["rayer-bazar", "Rayer Bazar", "রায়েরবাজার", 23.7350, 90.3600, "Rayer Bazar Dhaka", ["rayerbazar", "raer bazar", "রায়ের বাজার"], "", ""],
  ["hazaribagh", "Hazaribagh", "হাজারীবাগ", 23.7240, 90.3680, "Hazaribagh Dhaka", ["hazaribag", "হাজারিবাগ"], "", ""],
  ["lalbagh", "Lalbagh", "লালবাগ", 23.7190, 90.3880, "Lalbagh Fort Dhaka", ["lalbagh fort", "lalbag", "লালবাগ কেল্লা", "লালবাগ"], "", ""],
  ["chawkbazar", "Chawkbazar", "চকবাজার", 23.7170, 90.3960, "Chawkbazar Dhaka", ["chowkbazar", "chawk bazar", "চকবাজার", "চক বাজার"], "", ""],
  ["old-dhaka-shankhari-bazar", "Shankhari Bazar", "শাঁখারী বাজার", 23.7125, 90.4040, "Shankhari Bazar Dhaka", ["shakhari bazar", "শাখারি বাজার"], "", ""],
  ["aftabnagar", "Aftabnagar", "আফতাবনগর", 23.7640, 90.4490, "Aftabnagar Dhaka", ["aftab nagar", "আফতাব নগর"],
    "Take a rickshaw west to Rampura Bridge or Banasree, then board.",
    "রিকশায় পশ্চিমে রামপুরা ব্রিজ বা বনশ্রীতে এসে বাস ধরুন।"],
  ["hatirjheel", "Hatirjheel", "হাতিরঝিল", 23.7500, 90.4030, "Hatirjheel Dhaka", ["hatir jheel", "hatirjhil", "হাতিরঝিল"], "", ""],
  ["mugda", "Mugda", "মুগদা", 23.7290, 90.4350, "Mugda Dhaka", ["mugdapara", "মুগদাপাড়া", "মুগদা"], "", ""],
  ["maniknagar", "Maniknagar", "মানিকনগর", 23.7195, 90.4300, "Maniknagar Dhaka", ["manik nagar", "মানিক নগর"], "", ""],
  ["basabo", "Basabo", "বাসাবো", 23.7365, 90.4330, "Basabo Dhaka", ["bashabo", "বাসাবু"], "", ""],
  ["dania", "Dania", "দনিয়া", 23.7015, 90.4380, "Dania Dhaka", ["doniya", "দনিয়া"], "", ""],
  ["kamrangirchar", "Kamrangirchar", "কামরাঙ্গীরচর", 23.6990, 90.3790, "Kamrangirchar Dhaka", ["kamrangir char", "কামরাঙ্গীর চর"], "", ""],
  ["badda-link-road", "Badda Link Road", "বাড্ডা লিংক রোড", 23.7830, 90.4300, "Link Road Badda Dhaka", ["link road badda", "লিংক রোড"], "", ""],
  ["bijoy-sarani", "Bijoy Sarani", "বিজয় সরণি", 23.7650, 90.3850, "Bijoy Sarani Dhaka", ["bijoy shoroni", "বিজয় স্মরণী"], "", ""],
];

// route: [id, name_en, name_bn, service_type, hours, freq_min, freq_max, [stop ids in order]]
// service_type: "bus" | "minibus". company left empty until verified on the ground.
const R = (id, en, bn, type, from, to, fmin, fmax, stops) => ({
  id, name_en: en, name_bn: bn, company: "", service_type: type,
  hours: `${from}–${to}`, frequency_min: fmin, frequency_max: fmax, stops,
});

const CBD = ["farmgate", "karwan-bazar", "bangla-motor", "shahbag", "press-club", "paltan"];

export const ROUTES = [
  R("uttara-motijheel", "Uttara – Motijheel", "উত্তরা – মতিঝিল", "bus", "05:30", "22:30", 6, 12,
    ["abdullahpur", "uttara-hb", "azampur", "rajlokkhi", "jashimuddin", "airport", "khilkhet", "kuril", "kakoli", "banani", "mohakhali", ...CBD, "motijheel"]),
  R("uttara-gulistan", "Uttara – Gulistan", "উত্তরা – গুলিস্তান", "bus", "05:30", "22:00", 8, 15,
    ["abdullahpur", "uttara-hb", "rajlokkhi", "jashimuddin", "airport", "khilkhet", "kuril", "banani", "mohakhali", ...CBD, "gulistan"]),
  R("uttara-gulshan", "Uttara – Gulshan – Mohakhali", "উত্তরা – গুলশান – মহাখালী", "bus", "06:00", "21:30", 10, 18,
    ["abdullahpur", "uttara-hb", "azampur", "rajlokkhi", "jashimuddin", "airport", "khilkhet", "kuril", "notun-bazar", "gulshan-2", "gulshan-1", "mohakhali"]),
  R("gazipur-gulistan", "Gazipur – Tongi – Gulistan", "গাজীপুর – টঙ্গী – গুলিস্তান", "minibus", "05:00", "21:30", 10, 20,
    ["gazipur-chourasta", "tongi", "abdullahpur", "uttara-hb", "rajlokkhi", "jashimuddin", "airport", "khilkhet", "kuril", "banani", "mohakhali", ...CBD, "gulistan"]),
  R("mirpur12-motijheel", "Mirpur 12 – Motijheel", "মিরপুর ১২ – মতিঝিল", "bus", "05:30", "22:30", 5, 10,
    ["mirpur-12", "mirpur-11", "mirpur-10", "kazipara", "shewrapara", "agargaon", "farmgate", "karwan-bazar", "bangla-motor", "shahbag", "press-club", "paltan", "motijheel"]),
  R("mirpur10-gulistan", "Mirpur 10 – Gulistan", "মিরপুর ১০ – গুলিস্তান", "bus", "05:30", "22:30", 5, 10,
    ["mirpur-10", "kazipara", "shewrapara", "agargaon", "farmgate", "karwan-bazar", "bangla-motor", "shahbag", "press-club", "paltan", "gulistan"]),
  R("mirpur14-motijheel", "Mirpur 14 – Motijheel", "মিরপুর ১৪ – মতিঝিল", "bus", "06:00", "22:00", 8, 15,
    ["mirpur-14", "kazipara", "shewrapara", "agargaon", "farmgate", "karwan-bazar", "bangla-motor", "shahbag", "press-club", "paltan", "motijheel"]),
  R("mirpur1-sadarghat", "Mirpur 1 – Sadarghat", "মিরপুর ১ – সদরঘাট", "bus", "06:00", "21:30", 10, 18,
    ["mirpur-1", "mirpur-10", "kazipara", "shewrapara", "agargaon", "farmgate", "karwan-bazar", "bangla-motor", "shahbag", "press-club", "paltan", "gulistan", "nawabpur", "sadarghat"]),
  R("mirpur12-farmgate", "Mirpur 12 – Farmgate", "মিরপুর ১২ – ফার্মগেট", "minibus", "06:00", "22:00", 4, 8,
    ["mirpur-12", "mirpur-11", "mirpur-10", "kazipara", "shewrapara", "agargaon", "farmgate"]),
  R("mirpur-uttara", "Mirpur 10 – Kalshi – Uttara", "মিরপুর ১০ – কালশী – উত্তরা", "bus", "06:00", "21:30", 10, 20,
    ["mirpur-10", "mirpur-11", "mirpur-12", "kalshi", "uttara-hb", "abdullahpur"]),
  R("mirpur10-mohakhali", "Mirpur 12 – Kakoli – Mohakhali", "মিরপুর ১২ – কাকলী – মহাখালী", "bus", "06:00", "21:30", 10, 18,
    ["mirpur-12", "mirpur-11", "mirpur-10", "mirpur-14", "kakoli", "banani", "mohakhali", "gulshan-1"]),
  R("mohakhali-bashundhara", "Mohakhali – Gulshan – Bashundhara", "মহাখালী – গুলশান – বসুন্ধরা", "bus", "06:00", "21:30", 8, 15,
    ["mohakhali", "gulshan-1", "gulshan-2", "notun-bazar", "jamuna-future-park", "bashundhara"]),
  R("mirpur1-newmarket", "Mirpur 1 – Dhanmondi – New Market", "মিরপুর ১ – ধানমন্ডি – নিউ মার্কেট", "bus", "06:00", "22:00", 6, 12,
    ["mirpur-1", "technical", "kallyanpur", "shyamoli", "dhanmondi-27", "kalabagan", "science-lab", "new-market", "nilkhet", "azimpur"]),
  R("gabtoli-motijheel", "Gabtoli – Farmgate – Motijheel", "গাবতলী – ফার্মগেট – মতিঝিল", "bus", "05:30", "22:00", 8, 15,
    ["gabtoli", "technical", "kallyanpur", "shyamoli", "asad-gate", "farmgate", "karwan-bazar", "bangla-motor", "shahbag", "press-club", "paltan", "motijheel"]),
  R("savar-gulistan", "Savar – Gabtoli – Gulistan", "সাভার – গাবতলী – গুলিস্তান", "bus", "05:00", "21:30", 6, 12,
    ["savar", "aminbazar", "gabtoli", "technical", "kallyanpur", "shyamoli", "dhanmondi-27", "kalabagan", "science-lab", "new-market", "tsc", "shahbag", "press-club", "paltan", "gulistan"]),
  R("mohammadpur-gulshan", "Mohammadpur – Farmgate – Gulshan", "মোহাম্মদপুর – ফার্মগেট – গুলশান", "bus", "06:00", "21:30", 8, 15,
    ["mohammadpur", "asad-gate", "farmgate", "mohakhali", "gulshan-1", "gulshan-2"]),
  R("gulshan-motijheel", "Gulshan – Moghbazar – Motijheel", "গুলশান – মগবাজার – মতিঝিল", "bus", "06:00", "22:00", 8, 15,
    ["gulshan-2", "gulshan-1", "moghbazar", "mouchak", "shantinagar", "paltan", "motijheel"]),
  R("badda-gulistan", "Notun Bazar – Rampura – Gulistan", "নতুন বাজার – রামপুরা – গুলিস্তান", "bus", "06:00", "22:00", 6, 12,
    ["notun-bazar", "badda", "rampura", "malibagh", "mouchak", "shantinagar", "paltan", "gulistan"]),
  R("bashundhara-motijheel", "Bashundhara – Rampura – Motijheel", "বসুন্ধরা – রামপুরা – মতিঝিল", "bus", "06:00", "22:00", 6, 12,
    ["bashundhara", "jamuna-future-park", "notun-bazar", "badda", "rampura", "malibagh", "mouchak", "shantinagar", "paltan", "motijheel"]),
  R("kuril-sadarghat", "Kuril – Rampura – Sadarghat", "কুড়িল – রামপুরা – সদরঘাট", "bus", "06:00", "21:30", 8, 15,
    ["kuril", "notun-bazar", "badda", "rampura", "malibagh", "mouchak", "shantinagar", "paltan", "gulistan", "nawabpur", "sadarghat"]),
  R("banasree-motijheel", "Banasree – Rampura – Motijheel", "বনশ্রী – রামপুরা – মতিঝিল", "minibus", "06:00", "22:00", 5, 10,
    ["banasree", "rampura", "malibagh", "mouchak", "shantinagar", "paltan", "motijheel"]),
  R("khilgaon-gulistan", "Khilgaon – Malibagh – Gulistan", "খিলগাঁও – মালিবাগ – গুলিস্তান", "minibus", "06:00", "21:30", 6, 12,
    ["khilgaon", "malibagh", "mouchak", "shantinagar", "paltan", "gulistan"]),
  R("jatrabari-farmgate", "Jatrabari – Motijheel – Farmgate", "যাত্রাবাড়ী – মতিঝিল – ফার্মগেট", "bus", "05:30", "22:30", 5, 10,
    ["jatrabari", "sayedabad", "kamalapur", "motijheel", "paltan", "press-club", "shahbag", "bangla-motor", "karwan-bazar", "farmgate"]),
  R("jatrabari-sadarghat", "Jatrabari – Gulistan – Sadarghat", "যাত্রাবাড়ী – গুলিস্তান – সদরঘাট", "minibus", "05:30", "22:00", 4, 8,
    ["jatrabari", "sayedabad", "gulistan", "nawabpur", "sadarghat"]),
  R("mohakhali-azimpur", "Mohakhali – Farmgate – Azimpur", "মহাখালী – ফার্মগেট – আজিমপুর", "bus", "06:00", "22:00", 8, 15,
    ["mohakhali", "farmgate", "karwan-bazar", "bangla-motor", "shahbag", "tsc", "nilkhet", "azimpur"]),
  R("jigatola-gulistan", "Jigatola – Science Lab – Gulistan", "জিগাতলা – সায়েন্স ল্যাব – গুলিস্তান", "minibus", "06:00", "21:30", 6, 12,
    ["jigatola", "science-lab", "new-market", "tsc", "shahbag", "press-club", "paltan", "gulistan"]),
];
